#!/usr/bin/env bash
#
# Usage: basher _deps <package>
# Summary: Globally installs package runtime dependencies
#
# Installs the package dependencies, specified with the
# DEPS= variable on package.sh.
#
# Example: DEPS=username/repo1:otheruser/repo2

set -e

if [ "$#" -ne 1 ]; then
  basher-help _deps
  exit 1
fi

package="$1"

shopt -s nullglob

if [ "$NO_PACKAGE_SH" != "true" -a \
    -e "$BASHER_PACKAGES_PATH/$package/package.sh" ]; then
  source "$BASHER_PACKAGES_PATH/$package/package.sh"
fi

if [ -n "$DEPS" ]; then
  IFS=: read -a deps <<< "$DEPS"
else
  deps=()
fi

for dep in "${deps[@]}"
do
  basher-install "$dep"
done
