#!/usr/bin/env bash

package="$1"

shopt -s nullglob

if [ "$NO_PACKAGE_SH" != "true" -a \
    -e "$BASHER_PACKAGES_PATH/$package/package.sh" ]; then
  source "$BASHER_PACKAGES_PATH/$package/package.sh" # TODO: make this secure?
fi

if [ -n "$BASH_COMPLETIONS" ]; then
  IFS=: read -a bash_completions <<< "$BASH_COMPLETIONS"
else
  bash_completions=()
fi

if [ -n "$ZSH_COMPLETIONS" ]; then
  IFS=: read -a zsh_completions <<< "$ZSH_COMPLETIONS"
else
  zsh_completions=()
fi

for completion in "${bash_completions[@]}"
do
  rm -f "$BASHER_PREFIX/completions/bash/${completion##*/}"
done

for completion in "${zsh_completions[@]}"
do
  target="$BASHER_PACKAGES_PATH/$package/$completion"
  if grep -q "#compdef" "$target"; then
    rm -f "$BASHER_PREFIX/completions/zsh/compsys/${completion##*/}"
  else
    rm -f "$BASHER_PREFIX/completions/zsh/compctl/${completion##*/}"
  fi
done
